 var shuffleSequence = seq("intro", sepWith("sep", seq("practice", "message", rshuffle("critems", "eeg", "critems1", "filler", "fillerY", "fillerN"))));
var practiceItemTypes = ["practice"];
var showProgressBar = false;
var sendingResultsMessage = "Enviando resultados al servidor. No cierres esta página. ¡Gracias!";
var completionMessage = "¡Listo! Muchas gracias por participar.";

var equalGroupSizes = false;
var defaults = [
 
    "Separator", {
        transfer: 1000,
        normalMessage: "Esperá la próxima oración.",
        errorMessage: "Oops. Te equivocaste."
    },
    
    "AcceptabilityJudgment", {
        as: ["1", "2", "3", "4", "5"],
        presentAsScale: true,
        instructions: "Usá los números y letras del teclado para dar tu respuesta.",
        leftComment: "(Horrible)", rightComment: "(Perfecta)"
    
    },
    "Question", {
        hasCorrect: true
    },
    "Message", {
        hideProgressBar: true,
        requiresConsent: true,    
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true
    },
     "FlashSentence",{
         timeout: 5000
    }
    
];

var items = [

    // New in Ibex 0.3-beta-9. You can now add a '__SendResults__' controller in your shuffle
    // sequence to send results before the experiment has finished. This is NOT intended to allow
    // for incremental sending of results -- you should send results exactly once per experiment.
    // However, it does permit additional messages to be displayed to participants once the
    // experiment itself is over. If you are manually inserting a '__SendResults__' controller into
    // the shuffle sequence, you must set the 'manualSendResults' configuration variable to 'true', since
    // otherwise, results are automatically sent at the end of the experiment.
    //
    //["sr", "__SendResults__", { }],

    ["sep", "Separator", { }],

    // NOTE: You could also use the 'Message' controller for the experiment intro (this provides a simple
    // consent checkbox).
    ["intro", "Form", {
        html: { include: "example_intro.html" },
        validators: {
            edad: function (s) { if (s.match(/^\d+$/)) return true; else return "Valor incorrecto para \u2018edad\u2019"; }
        },
        continueMessage: "Hacé click aquí para continuar."
    } ],
    //
    // Three practice items for self-paced reading (one with a comprehension question).
    //
    ["practice", "AcceptabilityJudgment", {s: "Los estudiantes salieron de la escuela por la tarde. Esta es una oración que suena perfectamente. Presioná la opción 5 para indicar que es Perfectamente aceptable."},
     "Question",                         {q:"¿Los estudiantes salieron de la escuela por la mañana?", as: ["No", "Sí"]}],
    ["practice", "AcceptabilityJudgment", {s: "Los estudiantes por la tarde salieron de la escuela. Esta es una oración aceptable, pero no tan frecuente. Presioná la opción 4 para indicar que suena Bien"}],
    ["practice", "AcceptabilityJudgment", {s: "Por la tarde salieron de la escuela los estudiantes. Esta es una oración que está bien, pero sólo la dirías en contadas ocasiones. Presioná la opción 3 para indicar que suena Regular"}],  
    ["practice", "AcceptabilityJudgment", {s: "Por la tarde de la escuela salieron los estudiantes. Esta es una oración que es posible, pero suena muy extraña. Presioná la opción 2 para indicar que suena Rara"}],
    ["practice", "AcceptabilityJudgment", {s: "Los estudiantes por la tarde de la escuela salió. Esta es una oración que además de sonar rara, no respeta la gramática del español. Presioná la opción 1 para indicar que suena Horrible"}],
     ["message", "FlashSentence", {s: "Ahora vamos a empezar."}],
    //
    // Two "real" (i.e. non-filler) self-paced reading items with corresponding acceptability judgment items.
    // There are two conditions.
    //
[["critems",1],"AcceptabilityJudgment",{s:"La noticia la deprimió a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La noticia la deprime a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La abuela la deprimió a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La abuela la deprime a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La noticia le deprimió a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La noticia le deprime a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La abuela le deprimió a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"La abuela le deprime a María."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María la deprimió la noticia."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María la deprime la noticia."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María la deprimió la abuela."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María la deprime la abuela."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María le deprimió la noticia."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María le deprime la noticia."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María le deprimió la abuela."}],
[["critems",1],"AcceptabilityJudgment",{s:"A María le deprime la abuela."}],
[["critems",2],"AcceptabilityJudgment",{s:"El viaje lo ilusionó a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El viaje lo ilusiona a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El vendedor lo ilusionó a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El vendedor lo ilusiona a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El viaje le ilusionó a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El viaje le ilusiona a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El vendedor le ilusionó a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"El vendedor le ilusiona a Pedro."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro lo ilusionó el viaje."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro lo ilusiona el viaje."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro lo ilusionó el vendedor."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro lo ilusiona el vendedor."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro le ilusionó el viaje."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro le ilusiona el viaje."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro le ilusionó el vendedor."}],
[["critems",2],"AcceptabilityJudgment",{s:"A Pedro le ilusiona el vendedor."}],
[["critems",3],"AcceptabilityJudgment",{s:"La historieta la fascinó a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La historieta la fascina a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La gimnasta la fascinó a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La gimnasta la fascina a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La historieta le fascinó a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La historieta le fascina a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La gimnasta le fascinó a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"La gimnasta le fascina a Ana."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana la fascinó la historieta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana la fascina la historieta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana la fascinó la gimnasta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana la fascina la gimnasta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana le fascinó la historieta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana le fascina la historieta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana le fascinó la gimnasta."}],
[["critems",3],"AcceptabilityJudgment",{s:"A Ana le fascina la gimnasta."}],
[["critems",4],"AcceptabilityJudgment",{s:"La película lo divirtió a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La película lo divierte a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La animadora lo divirtió a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La animadora lo divierte a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La película le divirtió a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La película le divierte a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La animadora le divirtió a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"La animadora le divierte a Carlos."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos lo divirtió la película."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos lo divierte la película."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos lo divirtió la animadora."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos lo divierte la animadora."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos le divirtió la película."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos le divierte la película."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos le divirtió la animadora."}],
[["critems",4],"AcceptabilityJudgment",{s:"A Carlos le divierte la animadora."}],
[["critems",5],"AcceptabilityJudgment",{s:"La charla la entretuvo a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La charla la entretiene a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La recepcionista la entretuvo a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La recepcionista la entretiene a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La charla le entretuvo a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La charla le entretiene a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La recepcionista le entretuvo a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"La recepcionista le entretiene a Cecilia."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia la entretuvo la charla."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia la entretiene la charla."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia la entretuvo la recepcionista."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia la entretiene la recepcionista."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia le entretuvo la charla."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia le entretiene la charla."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia le entretuvo la recepcionista."}],
[["critems",5],"AcceptabilityJudgment",{s:"A Cecilia le entretiene la recepcionista."}],
[["critems",6],"AcceptabilityJudgment",{s:"El juego lo aburrió a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El juego lo aburre a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El profesor lo aburrió a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El profesor lo aburre a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El juego le aburrió a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El juego le aburre a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El profesor le aburrió a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"El profesor le aburre a Martín."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín lo aburrió el juego."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín lo aburre el juego."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín lo aburrió el profesor."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín lo aburre el profesor."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín le aburrió el juego."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín le aburre el juego."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín le aburrió el profesor."}],
[["critems",6],"AcceptabilityJudgment",{s:"A Martín le aburre el profesor."}],
[["critems",7],"AcceptabilityJudgment",{s:"El libro la interesó a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El libro la interesa a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El actor la interesó a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El actor la interesa a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El libro le interesó a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El libro le interesa a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El actor le interesó a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"El actor le interesa a Andrea."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea la interesó el libro."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea la interesa el libro."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea la interesó el actor."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea la interesa el actor."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea le interesó el libro."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea le interesa el libro."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea le interesó el actor."}],
[["critems",7],"AcceptabilityJudgment",{s:"A Andrea le interesa el actor."}],
[["critems",8],"AcceptabilityJudgment",{s:"El robo lo preocupó a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El robo lo preocupa a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El anciano lo preocupó a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El anciano lo preocupa a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El robo le preocupó a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El robo le preocupa a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El anciano le preocupó a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"El anciano le preocupa a Federico."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico lo preocupó el robo."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico lo preocupa el robo."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico lo preocupó el anciano."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico lo preocupa el anciano."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico le preocupó el robo."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico le preocupa el robo."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico le preocupó el anciano."}],
[["critems",8],"AcceptabilityJudgment",{s:"A Federico le preocupa el anciano."}],
[["critems",9],"AcceptabilityJudgment",{s:"El anuncio la tranquilizó a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El anuncio la tranquiliza a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El cura la tranquilizó a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El cura la tranquiliza a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El anuncio le tranquilizó a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El anuncio le tranquiliza a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El cura le tranquilizó a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"El cura le tranquiliza a Carolina."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina la tranquilizó el anuncio."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina la tranquiliza el anuncio."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina la tranquilizó el cura."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina la tranquiliza el cura."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina le tranquilizó el anuncio."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina le tranquiliza el anuncio."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina le tranquilizó el cura."}],
[["critems",9],"AcceptabilityJudgment",{s:"A Carolina le tranquiliza el cura."}],
[["critems",10],"AcceptabilityJudgment",{s:"El insulto lo ofendió a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El insulto lo ofende a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El guardia lo ofendió a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El guardia lo ofende a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El insulto le ofendió a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El insulto le ofende a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El guardia le ofendió a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"El guardia le ofende a Diego."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego lo ofendió el insulto."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego lo ofende el insulto."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego lo ofendió el guardia."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego lo ofende el guardia."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego le ofendió el insulto."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego le ofende el insulto."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego le ofendió el guardia."}],
[["critems",10],"AcceptabilityJudgment",{s:"A Diego le ofende el guardia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La clase la cansó a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La clase la cansa a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La profesora la cansó a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La profesora la cansa a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La clase le cansó a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La clase le cansa a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La profesora le cansó a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"La profesora le cansa a Silvia."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia la cansó las clases."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia la cansa esas clases."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia la cansó unas clases."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia la cansa la clase."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia le cansó unas clases."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia le cansa la clase."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia le cansó esa clase."}],
[["critems",11],"AcceptabilityJudgment",{s:"A Silvia le cansa una clase."}],
[["critems",12],"AcceptabilityJudgment",{s:"La burla lo enfureció a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La burla lo enfurece a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La secretaria lo enfureció a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La secretaria lo enfurece a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La burla le enfureció a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La burla le enfurece a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La secretaria le enfureció a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"La secretaria le enfurece a Jorge."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge lo enfureció la burla."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge lo enfurece la burla."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge lo enfureció la secretaria."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge lo enfurece la secretaria."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge le enfureció la burla."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge le enfurece la burla."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge le enfureció la secretaria."}],
[["critems",12],"AcceptabilityJudgment",{s:"A Jorge le enfurece la secretaria."}],
[["critems",13],"AcceptabilityJudgment",{s:"La oferta la entusiasmó a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La oferta la entusiasma a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La maestra la entusiasmó a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La maestra la entusiasma a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La oferta le entusiasmó a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La oferta le entusiasma a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La maestra le entusiasmó a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"La maestra le entusiasma a Sandra."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra la entusiasmó la oferta."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra la entusiasma la oferta."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra la entusiasmó la maestra."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra la entusiasma la maestra."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra le entusiasmó la oferta."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra le entusiasma la oferta."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra le entusiasmó la maestra."}],
[["critems",13],"AcceptabilityJudgment",{s:"A Sandra le entusiasma la maestra."}],
[["critems",14],"AcceptabilityJudgment",{s:"La máscara lo espantó a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La máscara lo espanta a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La vecina lo espantó a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La vecina lo espanta a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La máscara le espantó a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La máscara le espanta a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La vecina le espantó a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"La vecina le espanta a Guillermo."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo lo espantó la máscara."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo lo espanta la máscara."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo lo espantó la vecina."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo lo espanta la vecina."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo le espantó la máscara."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo le espanta la máscara."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo le espantó la vecina."}],
[["critems",14],"AcceptabilityJudgment",{s:"A Guillermo le espanta la vecina."}],
[["critems",15],"AcceptabilityJudgment",{s:"La explosión la asustó a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La explosión la asusta a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La policía la asustó a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La policía la asusta a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La explosión le asustó a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La explosión le asusta a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La policía le asustó a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"La policía le asusta a Patricia."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia la asustó la explosión."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia la asusta la explosión."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia la asustó la policía."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia la asusta la policía."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia le asustó la explosión."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia le asusta la explosión."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia le asustó la policía."}],
[["critems",15],"AcceptabilityJudgment",{s:"A Patricia le asusta la policía."}],
[["critems",16],"AcceptabilityJudgment",{s:"El ruido lo molestó a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El ruido lo molesta a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El chico lo molestó a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El chico lo molesta a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El ruido le molestó a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El ruido le molesta a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El chico le molestó a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"El chico le molesta a Juan."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molestó el ruido."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molesta el ruido."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molestó el chico."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molesta el chico."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molestó el ruido."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan lo molesta el ruido."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan le molestó el chico."}],
[["critems",16],"AcceptabilityJudgment",{s:"A Juan le molesta el chico."}],
[["critems",17],"AcceptabilityJudgment",{s:"La carta la decepcionó a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La carta la decepciona a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La cantante la decepcionó a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La cantante la decepciona a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La carta le decepcionó a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La carta le decepciona a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La cantante le decepcionó a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"La cantante le decepciona a Jimena."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena la decepcionó la carta."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena la decepciona la carta."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena la decepcionó la cantante."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena la decepciona la cantante."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena le decepcionó la carta."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena le decepciona la carta."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena le decepcionó la cantante."}],
[["critems",17],"AcceptabilityJudgment",{s:"A Jimena le decepciona la cantante."}],
[["critems",18],"AcceptabilityJudgment",{s:"El cuento lo asombró a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El cuento lo asombra a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El mago lo asombró a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El mago lo asombra a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El cuento le asombró a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El cuento le asombra a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El mago le asombró a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"El mago le asombra a Nicolás."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás lo asombró el cuento."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás lo asombra el cuento."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás lo asombró el mago."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás lo asombra el mago."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás le asombró el cuento."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás le asombra el cuento."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás le asombró el mago."}],
[["critems",18],"AcceptabilityJudgment",{s:"A Nicolás le asombra el mago."}],
[["critems",19],"AcceptabilityJudgment",{s:"El chisme la sorprendió a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El chisme la sorprende a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El atentado la sorprendió a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El atentado la sorprende a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El chisme le sorprendió a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El chisme le sorprende a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El atentado le sorprendió a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"El atentado le sorprende a Florencia."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia la sorprendió el chisme."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia la sorprende el chisme."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia la sorprendió el atentado."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia la sorprende el atentado."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia le sorprendió el chisme."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia le sorprende el chisme."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia le sorprendió el atentado."}],
[["critems",19],"AcceptabilityJudgment",{s:"A Florencia le sorprende el atentado."}],
[["critems",20],"AcceptabilityJudgment",{s:"El libro lo conmovió a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El libro lo conmueve a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El indigente lo conmovió a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El indigente lo conmueve a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El libro le conmovió a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El libro le conmueve a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El indigente le conmovió a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"El indigente le conmueve a José."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José lo conmovió el libro."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José lo conmueve el libro."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José lo conmovió el indigente."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José lo conmueve el indigente."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José le conmovió el libro."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José le conmueve el libro."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José le conmovió el indigente."}],
[["critems",20],"AcceptabilityJudgment",{s:"A José le conmueve el indigente."}],
    
    ["filler", "AcceptabilityJudgment", {s: "Los trabajadores han decidido volver a la huelga al no lograrse avances en las últimas negociaciones con representantes de la compañía."}],
    ["filler", "AcceptabilityJudgment", {s: "José engañó a su mujer con la mejor amiga de Clara."}],
    ["filler", "AcceptabilityJudgment", {s: "Los nuevos muebles serán acomodados de acuerdo con las órdenes del inquilino de la oficina."}],
    ["filler", "AcceptabilityJudgment", {s: "El telegrama ordena que el banco se prepare para recibir al grupo de inversores."}],
    ["filler", "AcceptabilityJudgment", {s: "El secretario subrayó que el general conservador queda totalmente deslegitimado."}],
    ["filler", "AcceptabilityJudgment", {s: "El pastor les dio su bendición a los fieles de la parroquia."}],
    ["filler", "AcceptabilityJudgment", {s: "El alemán abandonó a su mujer luego de que ella se burlara de él."}],
    ["filler", "AcceptabilityJudgment", {s: "Los colegas se abrazan después de no haberse visto por un largo tiempo."}],
    ["filler", "AcceptabilityJudgment", {s: "La gente se acostumbra a los cambios abruptos cuando el país vive en crisis."}],
    ["filler", "AcceptabilityJudgment", {s: "La gimnasta bautizó al bebé con el nombre de Tomás."}],
    ["filler", "AcceptabilityJudgment", {s: "Los compañeros de la oficina le celebraron el cumpleaños a Sara esa misma tarde."}],
    ["filler", "AcceptabilityJudgment", {s: "A Estefanía le envían cartas a la dirección equivocada."}],
    ["filler", "AcceptabilityJudgment", {s: "El intendente hizo evacuar la ciudad después de las inundaciones."}],
    ["filler", "AcceptabilityJudgment", {s: "Al chofer le deben el salario desde hace tres meses."}],
    ["filler", "AcceptabilityJudgment", {s: "El novio le compone una canción de amor a Martina."}],
    ["filler", "AcceptabilityJudgment", {s: "La entrevista con el científico entusiasmó a los investigadores durante la universidad."}],
    ["filler", "AcceptabilityJudgment", {s: "La pareja le devolvió el dinero prestado al banco y finalmente saldó su deuda."}],
    ["filler", "AcceptabilityJudgment", {s: "A los comensales les cayó mal la comida y hubo que a la ambulancia llamar."}],
    ["filler", "AcceptabilityJudgment", {s: "El futbolista pateó la pelota hacia el delantero del equipo."}],
    ["filler", "AcceptabilityJudgment", {s: "La muchacha se enteró de lo sucedido e inmediatamente llamó con su amiga."}],
    ["filler", "AcceptabilityJudgment", {s: "La visita inesperada de la tía generó malestar de la familia."}],
    ["filler", "AcceptabilityJudgment", {s: "La actriz sin trabajo se quedó después del fracaso de la obra."}],
    ["filler", "AcceptabilityJudgment", {s: "El ama de casa se tiñe el pelo en su hogar por recortar gastos."}],
    ["filler", "AcceptabilityJudgment", {s: "La mala ubicación del hospital dificulta que los pacientes con facilidad lo encuentren."}],
    ["filler", "AcceptabilityJudgment", {s: "El martes pasado a María Inés el auto le robaron mientras estaba en una fiesta."}],
    
    ["fillerN", "AcceptabilityJudgment", {s: "Aunque los médicos hicieron todo lo que estuvo a su alcance, el paciente a la cirugía no sobrevivió."},
    "Question",                         {q:"¿El paciente murió por un error médico?" ,as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Cuando necesitan comer los mendigos va al comedor municipal."},
    "Question",                         {q:"¿El comedor municipal recibe a los mendigos?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Mientras jugaba al tenis Andrés se quebró la muñeca y su hermano a la sala de urgencias lo llevó."},
    "Question",                         {q:"¿Es el hermano de Andrés quien estaba jugando al tenis?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "El año pasado participó la compañía del concurso y ganó tres premios."},
    "Question",                         {q:"¿El año pasado fue un buen año para la compañía?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Todas las mañanas al guardia del edificio le muestra sus credenciales el oficinista."},
    "Question",                         {q:"¿Es el guardia quien muestra sus credenciales por la mañana?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Apenas se enteró de las novedades Andrea con los reporteros del canal de televisión colaboró."},
    "Question",                         {q:"¿Andrea habló con los periodistas?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Desde que se compró los zapato, a Sergio le duelen los pies."},
    "Question",                         {q:"¿Sergio tuvo siempre dolor de pies?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Durante este semestre el alumno sólo se sacó buenas notas y de sus profesores recibió felicitaciones."},
    "Question",                         {q:"¿Los profesores apoyaron el esfuerzo del alumno?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Aunque no sepa bailar muy bien, la gracia y belleza de la muchacha despiertan la admiración de su compañero."},
    "Question",                         {q:"¿El muchacho admira cómo baila la chica?",as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Una hora antes de la función, escenógrafos terminaron de montar la escena."},
    "Question",                         {q:"¿El montaje de la obra terminó a último momento?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Siempre que está nublado la anciana tiene malos presentimientos sobre la salud de su marido."},
    "Question",                         {q:"¿Murió el marido de la anciana?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Después del partido al árbitro le tiraron botellas de vidrio y piedras por sus malas decisiones."},
    "Question",                         {q:"¿Trataron de herir al árbitro?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Siempre que tiene un examen Mariana repite la lección a sus primas y tíos."},
    "Question",                         {q:"¿Son las primas quienes repiten la lección?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Antes de hacer la masa se debe precalentar el horno a temperatura moderada."},
    "Question",                         {q:"¿La masa debe hacerse después de prender el horno?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Como no llueva, los granjeros perderán la cosecha de soja de este año."},
    "Question",                         {q:"¿Los granjeros están preocupados por el exceso de lluvia?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Aunque los sindicatos se rehúsan a levantar la protesta, muchos camioneros siguen trabajando."},
    "Question",                         {q:"¿La protesta continúa?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Para tener éxito en la pesca de trucha se debe tener paciencia y buena carnada."},
    "Question",                         {q:"¿El consejo es sobre la cría de trucha?",as: ["No", "Sí"]}] ,
    ["fillerY", "AcceptabilityJudgment", {s: "Porque encontrar el amor es difícil muchas personas acuden a profesionales y grupos de ayuda."},
    "Question",                         {q:"¿Son los profesionales quienes pueden dar ayuda?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Debido a la peste los terratenientes sacrificaron gran parte de su ganado."},
    "Question",                         {q:"¿El ganado fue sacrificado antes de la peste?",as: ["No", "Sí"]}] ,
    ["fillerY", "AcceptabilityJudgment", {s: "En vez de resolver los problemas inmediatos, el partido trazó un plan de trabajo a largo plazo."},
    "Question",                         {q:"¿El plan contempla posibles problemas en el futuro?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Una vez que se comete un delito, es muy difícil conseguir que el Estado nos crea de nuevo."},
    "Question",                         {q:"¿Es el Estado quien comete el delito?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "A pesar de que frecuentemente se pintan las aulas, las condiciones de la universidad pública son cada vez más deplorables."},
    "Question",                         {q:"¿Se hacen trabajos de mantenimiento en la universidad?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Si bien se redujo el crimen en la ciudad, la gente todavía vive con miedo."},
    "Question",                         {q:"¿Hay más crimen en la ciudad?", as: ["No", "Sí"]}],
    ["fillerY", "AcceptabilityJudgment", {s: "Una vez a la semana el panadero le paga a los proveedores de harina."},
    "Question",                         {q:"¿Es constante el panadero con sus pagos?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Para modificar la ley es necesario que ambas cámaras aprueben el proyecto con más de dos tercios de los votos."},
    "Question",                         {q:"¿Puede una sola cámara modificar la ley si tiene la mayoría de los votos?", as: ["No", "Sí"]}],
     
    ["fillerY", "AcceptabilityJudgment", {s: "El gato del tercer piso maúlla siempre que sus dueños lo dejan solo."},
    "Question",                         {q:"¿Tiene más de un dueño el gato?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Marta le contó la historia a su hija cuando su hermano cumplió la mayoría de edad."},
    "Question",                         {q:"¿La hija de Marta se enteró de la historia a través de su hermano?", as: ["No", "Sí"]}],         
    ["fillerY", "AcceptabilityJudgment", {s: "Todos los payasos llevan sombrero de color rojo menos uno"},
    "Question",                         {q:"¿Hay algún payaso que no lleve sombrero rojo?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Sólo algunas personas votaron en las últimas elecciones barriales."},
    "Question",                         {q:"¿Los resultados de la votación representaron la elección de todos los vecinos?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "El senador donó una gran suma de dinero a los directores de la biblioteca."},
    "Question",                         {q:"¿La donación vino de parte de un miembro del gobierno?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "En la fábrica descubrieron que no todos los empleados estaban capacitados para utilizar las nuevas máquinas."},
    "Question",                         {q:"¿Todos los empleados son competentes?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "El dibujante le entregó los bocetos al editor durante la entrevista."},
    "Question",                         {q:"¿Es el editor quien recibió los dibujos?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "No serán aceptadas por la agencia aquellas personas que no presenten los papeles necesarios."},
    "Question",                         {q:"¿Es conveniente que las personas que no tienen todos los papeles se presenten?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "Las autoridades sanitarias combatieron la plaga adecuadamente."},
    "Question",                         {q:"¿Ha desaparecido la plaga?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Esa tarde Federico convenció a Luciana de ir a la playa."},
    "Question",                         {q:"¿Federico habló con Luciana por la mañana para convencerla de ir a la playa?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "La encargada del edificio confesó que había robado el dinero."},
    "Question",                         {q:"¿Apareció el ladrón del dinero?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Cuando la anciana se fue, sus amigas la criticaron por su vestimenta inadecuada."},
    "Question",                         {q:"¿La anciana estaba presente cuando sus amigas la criticaron?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "Nadie conoce a la pianista nueva del restaurante."},
    "Question",                         {q:"¿El personal del restaurante tiene un integrante más?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Con mucho esfuerzo, los amigos de José juntaron el dinero para que pudiera arreglar su auto."},
    "Question",                         {q:"¿Los amigos de José arreglaron su auto?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "El libro contiene textos de autores antiguos y una reseña de gran parte de sus obras."},
    "Question",                         {q:"¿El libro contiene obras de más de un autor?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Al asesino lo condenaron a cuarenta años de prisión."},
    "Question",                         {q:"¿El asesino recibió una condena corta?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "El tutor le corrigió los errores al chico rubio."},
    "Question",                         {q:"¿El tutor realizó su trabajo?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Mientras el hombre cazaba, las mujeres se entretenían en la casa."},
    "Question",                         {q:"¿Las mujeres acompañaron a los hombres?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "La recepcionista le comunicó al gerente las noticias de esa mañana."},
    "Question",                         {q:"¿El gerente recibió las novedades?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Para la noche, los albañiles habían terminado de construir las paredes."},
    "Question",                         {q:"¿Los obreros terminaron con las paredes por la mañana?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "El músico le copió su número de teléfono en un papel a la trompetista de orquesta."},
    "Question",                         {q:"¿El músico quería que la trompetista se comunicara con él?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "El pago se efectuó a fin de mes, y los becarios volvieron a trabajar."},
    "Question",                         {q:"¿Los becarios trabajaron durante todo el mes?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "Los niños guardaron los juguetes de su hermana en el armario."},
    "Question",                         {q:"¿El dueño de los juguetes es una chica?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Silvia guió a su amiga hasta la puerta principal de la casa y se despidió."},
    "Question",                         {q:"¿La casa es de la amiga de Silvia?", as: ["No", "Sí"]}],     
    ["fillerY", "AcceptabilityJudgment", {s: "Después de mezclar la sal, los huevos y el harina, hay que dejar reposar la mezcla por media hora."},
    "Question",                         {q:"¿La masa lleva harina y huevos?", as: ["Sí", "No"]}],
    ["fillerN", "AcceptabilityJudgment", {s: "Mario le presentó su mujer al traumatólogo del hospital."},
    "Question",                         {q:"¿El médico conocía a la mujer de Mario?", as: ["No", "Sí"]}]        
];
    